name: TEST
on: 
  repository_dispatch:
    types:
      - zqhTest

jobs:
  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          BUILD_RBD_APP_UI: false
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAMESPACE: ${{ secrets.IMAGE_NAMESPACE }}
          VERSION: ${{ github.event.client_payload.branch }}-dev
        run: |
          git clone -b ${{ github.event.client_payload.branch }} https://github.com/ZhangSetSail/rainbond-ui.git        
          cd rainbond-ui
          chmod +x ./build.sh
          ./build.sh
          
  build-rainbond-allinone:
    needs: build-ui
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Log in to the mirror repository
        run: echo "${{ secrets.DOMESTIC_DOCKER_PASSWORD }}" | docker login ${{ secrets.DOMESTIC_BASE_NAME }} -u ${{ secrets.DOMESTIC_DOCKER_USERNAME }} --password-stdin
        
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 yapf==0.26.0
        
      - name: Pull code and Build allinone image
        env:
          VERSION: ${{ github.event.client_payload.branch }}-dev
          TRAVIS_PULL_REQUEST: false
          DOMESTIC_NAMESPACE: ${{ secrets.DOMESTIC_NAMESPACE }}
          DOMESTIC_DOCKER_PASSWORD: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}
          DOMESTIC_DOCKER_USERNAME: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAMESPACE: ${{ secrets.IMAGE_NAMESPACE }}
          DOMESTIC_BASE_NAME: ${{ secrets.DOMESTIC_BASE_NAME }}
        run: |
          git clone -b ${{ github.event.client_payload.branch }} https://github.com/ZhangSetSail/rainbond-console.git   
          cd rainbond-console
          chmod +x  ./release.sh
          ./release.sh allinone
  
  build-rainbond-region:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.13

      - name: Log in to the mirror repository
        run: echo "${{ secrets.DOMESTIC_DOCKER_PASSWORD }}" | docker login ${{ secrets.DOMESTIC_BASE_NAME }} -u ${{ secrets.DOMESTIC_DOCKER_USERNAME }} --password-stdin

      - name: Pull code and Build the Docker image
        env:
          VERSION: ${{ github.event.client_payload.branch }}-dev
          DISABLE_GOPROXY: true
          DOMESTIC_BASE_NAME: ${{ secrets.DOMESTIC_BASE_NAME }}
          
          IMAGE_NAMESPACE: ${{ secrets.IMAGE_NAMESPACE }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          
          DOMESTIC_DOCKER_PASSWORD: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}
          DOMESTIC_DOCKER_USERNAME: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          DOMESTIC_NAMESPACE: ${{ secrets.DOMESTIC_NAMESPACE }}
        run: |
          git clone -b ${{ github.event.client_payload.branch }} https://github.com/ZhangSetSail/rainbond.git
          cd rainbond
          chmod +x ./release.sh
          ./release.sh all push
          
  build-operator:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          # The Go version to download (if necessary) and use. Supports semver spec and ranges.
          go-version: 1.15
      - name: install-golint
        run: go get -u golang.org/x/lint/golint
        
      - name: Build and push
        env:
          IMAGE_NAMESPACE: ${{ secrets.IMAGE_NAMESPACE }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          VERSION: ${{ github.event.client_payload.branch }}-dev
        run: |
          git clone -b release-2.1 https://github.com/ZhangSetSail/rainbond-operator.git
          cd rainbond-operator
          ./check.sh
          chmod +x ./release.sh
          ./release.sh        
