name: TEST
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        env:
          TRAVIS_PULL_REQUEST: false
          BUILD_RBD_APP_UI: false
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOMESTIC_DOCKER_PASSWORD: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}
          DOMESTIC_DOCKER_USERNAME: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          IMAGE_NAMESPACE: "zhangsetsail"
          DOMESTIC_BASE_NAME: "zhangqh@goodrain.onaliyun.com"
          NNNN: ${{ NNNN }}
          
        run: 
          echo ${NNNN}
          VERSION=v5.5.0-dind ./build.sh
