name: TEST
on: 
  repository_dispatch:
    types:
      - zqhTest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          TRAVIS_PULL_REQUEST: false
          BUILD_RBD_APP_UI: false
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOMESTIC_DOCKER_PASSWORD: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}
          DOMESTIC_DOCKER_USERNAME: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          IMAGE_NAMESPACE: ${{ secrets.IMAGE_NAMESPACE }}
          DOMESTIC_BASE_NAME: ${{ secrets.DOMESTIC_BASE_NAME }}
          VERSION: ${{ github.event.client_payload.branch }}
        run: 
          git clone -b ${{ github.event.client_payload.branch }} https://${{ secrets.GITHUB_USER }}:"${{ secrets.GITHUB_PASSWORD }}"git@github.com:ZhangSetSail/rainbond-ui.git
          cd rainbond-ui-cloud
          chmod +x ./build.sh
          ./build.sh
